# gateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aluno-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aluno
  template:
    metadata:
      labels:
        app: aluno
    spec:
      containers:
      - name: aluno
        image: fernandowi55/aluno:latest
        ports:
        - containerPort: 8080
#         env:
#         - name: eureka.client.service-url.defaultZone
#           value: http://store-discovery:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: aluno-service
spec:
  selector:
    app: aluno


   
     

